# Generated by Django 4.2.13 on 2024-05-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_course_customuser_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='validity',
            field=models.DateField(blank=True, null=True),
        ),
    ]
