# Generated by Django 4.2.13 on 2024-05-24 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_course_remove_customuser_validity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
