# Generated by Django 4.2.13 on 2024-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('courseCode', models.CharField(max_length=100)),
                ('coursePhoto', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
