# Generated by Django 4.2.13 on 2024-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customuser_validity_alter_customuser_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_detail',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
