# Generated by Django 4.2.13 on 2024-05-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_customuser_payment_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseDescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
