# Generated by Django 4.2.13 on 2024-07-15 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterCode', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=200)),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
            ],
        ),
        migrations.CreateModel(
            name='correctOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctOpt', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='weightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='geomaticsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('publish', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.chapter')),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage')),
            ],
        ),
    ]
