# Generated by Django 4.2.13 on 2024-05-22 10:10

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='correctOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correctOpt', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='spatialDataManagementSystemAndSpatialDataInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
        migrations.CreateModel(
            name='projectPlanningDesignAndImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
        migrations.CreateModel(
            name='photogrammetryRemoteSensingandImageProcessing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
        migrations.CreateModel(
            name='GlobalNavigationSatelliteSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
        migrations.CreateModel(
            name='geographicInformationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
        migrations.CreateModel(
            name='geodesyAndGravityField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
        migrations.CreateModel(
            name='fundamentalsOfSurveying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
        migrations.CreateModel(
            name='engineeringSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
        migrations.CreateModel(
            name='cartographyAndGeoVisualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
        migrations.CreateModel(
            name='cadasterLanduseAndLandManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
    ]
