# Generated by Django 4.2.13 on 2024-05-23 04:37

from django.db import migrations, models
import django.db.models.deletion
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geomatics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterCode', models.CharField(max_length=30)),
                ('chapterName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', django_quill.fields.QuillField()),
                ('option1', django_quill.fields.QuillField()),
                ('option2', django_quill.fields.QuillField()),
                ('option3', django_quill.fields.QuillField()),
                ('option4', django_quill.fields.QuillField()),
                ('explanation', django_quill.fields.QuillField()),
                ('correctOpt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geomatics.correctoption')),
            ],
        ),
    ]
