# Generated by Django 4.2.13 on 2024-05-23 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geomatics', '0002_chapter_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='weightage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
            ],
        ),
    ]
