# Generated by Django 4.2.13 on 2024-05-23 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomatics', '0003_weightage'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
    ]
