# Generated by Django 4.2.13 on 2024-05-23 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geomatics', '0005_questions_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadasterlanduseandlandmanagement',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cadasterlanduseandlandmanagement',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartographyandgeovisualization',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartographyandgeovisualization',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engineeringsurvey',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='engineeringsurvey',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundamentalsofsurveying',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fundamentalsofsurveying',
            name='weight',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geodesyandgravityfield',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geodesyandgravityfield',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geographicinformationsystem',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='geographicinformationsystem',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='globalnavigationsatellitesystem',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalnavigationsatellitesystem',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photogrammetryremotesensingandimageprocessing',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photogrammetryremotesensingandimageprocessing',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectplanningdesignandimplementation',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectplanningdesignandimplementation',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='spatialdatamanagementsystemandspatialdatainfrastructure',
            name='publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spatialdatamanagementsystemandspatialdatainfrastructure',
            name='weight',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geomatics.weightage'),
            preserve_default=False,
        ),
    ]
