# Generated by Django 4.2.13 on 2024-05-25 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomatics', '0008_rename_questions_geomaticsquestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='courses',
        ),
    ]
