# Generated by Django 4.2.13 on 2024-05-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geomatics', '0010_chapter_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='course',
        ),
    ]
