# Generated by Django 4.2.13 on 2024-05-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('civil', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='questions',
            new_name='civilQuestions',
        ),
    ]
